-- Seed the global exercise library (owner_id = null, visible to everyone).
-- Aliases are what the LLM will normalize toward these canonical names.

insert into public.exercises (owner_id, canonical_name, category, aliases, default_unit) values
-- ── Strength (barbell / dumbbell / machine) ──────────────────
(null, 'Bench Press',             'strength',   array['bp','bench','flat bench','barbell bench','bench press'], 'lb'),
(null, 'Incline Bench Press',     'strength',   array['incline bench','incline press','ibp','incline bench press'], 'lb'),
(null, 'Decline Bench Press',     'strength',   array['decline bench','decline press','decline bench press'], 'lb'),
(null, 'Dumbbell Bench Press',    'strength',   array['db bench','dumbbell bench','db bench press'], 'lb'),
(null, 'Dumbbell Incline Press',  'strength',   array['db incline','incline db','incline dumbbell press'], 'lb'),
(null, 'Squat',                   'strength',   array['squats','back squat','bb squat','barbell squat'], 'lb'),
(null, 'Front Squat',             'strength',   array['fs','front squats'], 'lb'),
(null, 'Deadlift',                'strength',   array['dl','deads','deadlifts','conventional deadlift'], 'lb'),
(null, 'Romanian Deadlift',       'strength',   array['rdl','romanian dl','romanian deadlifts'], 'lb'),
(null, 'Sumo Deadlift',           'strength',   array['sumo','sumo dl'], 'lb'),
(null, 'Overhead Press',          'strength',   array['ohp','press','military press','shoulder press','standing press'], 'lb'),
(null, 'Push Press',              'strength',   array['pp'], 'lb'),
(null, 'Barbell Row',             'strength',   array['bb row','bent over row','bent-over row','row'], 'lb'),
(null, 'Pendlay Row',             'strength',   array['pendlay'], 'lb'),
(null, 'T-Bar Row',               'strength',   array['tbar','t bar row','tbar row'], 'lb'),
(null, 'Dumbbell Row',            'strength',   array['db row','one arm row','single arm row'], 'lb'),
(null, 'Dumbbell Shoulder Press', 'strength',   array['db ohp','db press','db shoulder press'], 'lb'),
(null, 'Lateral Raise',           'strength',   array['lat raise','side raise','lateral raises'], 'lb'),
(null, 'Dumbbell Curl',           'strength',   array['db curl','bicep curl','biceps curl','curls'], 'lb'),
(null, 'Barbell Curl',            'strength',   array['bb curl','barbell curls'], 'lb'),
(null, 'Hammer Curl',             'strength',   array['hammers','hammer curls'], 'lb'),
(null, 'Skullcrusher',            'strength',   array['skullcrushers','lying tricep extension','lying triceps extension'], 'lb'),
(null, 'Tricep Pushdown',         'strength',   array['pushdown','rope pushdown','tricep pushdowns','triceps pushdown'], 'lb'),
(null, 'Face Pull',               'strength',   array['face pulls'], 'lb'),
(null, 'Lat Pulldown',            'strength',   array['pulldown','lat pulldowns','pulldowns'], 'lb'),
(null, 'Seated Cable Row',        'strength',   array['cable row','seated row'], 'lb'),
(null, 'Leg Press',               'strength',   array['lp'], 'lb'),
(null, 'Leg Curl',                'strength',   array['hamstring curl','ham curl','leg curls'], 'lb'),
(null, 'Leg Extension',           'strength',   array['leg ext','leg extensions','quad extension'], 'lb'),
(null, 'Calf Raise',              'strength',   array['calves','standing calf raise','calf raises'], 'lb'),
(null, 'Hip Thrust',              'strength',   array['hip thrusts','barbell hip thrust'], 'lb'),
(null, 'Bulgarian Split Squat',   'strength',   array['bss','bulgarian split squats','split squat'], 'lb'),
(null, 'Lunge',                   'strength',   array['lunges','walking lunge','walking lunges'], 'lb'),
(null, 'Good Morning',            'strength',   array['good mornings','gm'], 'lb'),
(null, 'Pec Deck',                'strength',   array['chest fly','chest flye','pec flye'], 'lb'),

-- ── Cardio ───────────────────────────────────────────────────
(null, 'Run',                     'cardio',     array['running','jog','jogging','outdoor run'], 'mi'),
(null, 'Treadmill Run',           'cardio',     array['treadmill','tread run'], 'mi'),
(null, 'Cycle',                   'cardio',     array['bike','cycling','bicycle','biking','outdoor ride'], 'mi'),
(null, 'Stationary Bike',         'cardio',     array['spin','spin bike','indoor bike'], 'mi'),
(null, 'Row',                     'cardio',     array['rowing','erg','rower','concept 2','c2'], 'm'),
(null, 'Swim',                    'cardio',     array['swimming','swam'], 'm'),
(null, 'Elliptical',              'cardio',     array['elliptical trainer'], 'mi'),
(null, 'Stair Climber',           'cardio',     array['stairs','stairmaster','stair master'], 'm'),
(null, 'Walk',                    'cardio',     array['walking','walked'], 'mi'),
(null, 'Hike',                    'cardio',     array['hiking','hiked'], 'mi'),

-- ── Bodyweight / calisthenics ────────────────────────────────
(null, 'Push-up',                 'bodyweight', array['pushups','pushup','push ups','press up','press-ups'], 'reps'),
(null, 'Pull-up',                 'bodyweight', array['pullups','pullup','pull ups','chin-up','chinup','chin ups'], 'reps'),
(null, 'Dip',                     'bodyweight', array['dips','bar dip','parallel bar dip'], 'reps'),
(null, 'Plank',                   'bodyweight', array['planks','front plank'], 'reps'),
(null, 'Sit-up',                  'bodyweight', array['situps','situp','sit ups'], 'reps'),
(null, 'Crunch',                  'bodyweight', array['crunches','ab crunch'], 'reps'),
(null, 'Leg Raise',               'bodyweight', array['leg raises','hanging leg raise','lying leg raise'], 'reps'),
(null, 'Burpee',                  'bodyweight', array['burpees'], 'reps'),
(null, 'Mountain Climber',        'bodyweight', array['mountain climbers','mt climbers'], 'reps'),
(null, 'Jumping Jack',            'bodyweight', array['jumping jacks','jjs','star jumps'], 'reps'),
(null, 'Air Squat',               'bodyweight', array['bodyweight squat','bw squat','squat jumps'], 'reps');
